In [1]:
import numpy as np

In [4]:
# Create a diagonal matrix
D = np.diag([1, 2, 3, 4])
print(D)

A = np.array([[1, 2, 3, 4], [1,2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(A)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [13]:
print(D @ A) # row scaling
print()
print(A @ D) # col scaling
print()
print(D @ D) # row and col scaling

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]

[[ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]]

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [14]:
# Create two upper triangular matrices
U1 = np.triu(np.random.randint(1, 10, size=(4, 4)))
U2 = np.triu(np.random.randint(1, 10, size=(4, 4)))

print("Upper Triangular Matrix U1:")
print(U1)
print("\nUpper Triangular Matrix U2:")
print(U2)

# Matrix multiplication of the two upper triangular matrices
result = U1 @ U2

print("\nResult of U1 @ U2:")
print(result)

Upper Triangular Matrix U1:
[[5 4 3 5]
 [0 6 5 3]
 [0 0 2 5]
 [0 0 0 6]]

Upper Triangular Matrix U2:
[[7 5 4 1]
 [0 8 2 4]
 [0 0 8 5]
 [0 0 0 6]]

Result of U1 @ U2:
[[35 57 52 66]
 [ 0 48 52 67]
 [ 0  0 16 40]
 [ 0  0  0 36]]


In [ ]:
matrix1 = np.random.randint(1, 10, size=(6, 6))
matrix2 = np.random.randint(1, 10, size=(6, 6))

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

result_6x6 = matrix1 @ matrix2

print("\nResult of Matrix 1 @ Matrix 2:")
print(result_6x6)

Matrix 1:
[[1 1 5 9 8 7]
 [5 5 5 4 7 5]
 [6 9 2 7 7 4]
 [8 5 3 1 8 7]
 [8 9 1 3 1 7]
 [2 2 6 5 8 5]]

Matrix 2:
[[4 1 4 3 3 1]
 [9 2 7 9 2 8]
 [2 3 1 6 5 7]
 [3 8 3 7 3 2]
 [3 4 1 2 3 9]
 [3 1 7 6 8 1]]

Result of Matrix 1 @ Matrix 2:
[[ 95 129 100 163 137 141]
 [123  95 114 162 123 156]
 [163 118 145 198 120 173]
 [131  74 130 152 132 150]
 [148  64 155 176 115 109]
 [ 92 101  86 141 119 147]]


In [18]:
A1 = np.array([[1, 1, 5, 9, 8, 7], [5,5,5,4,7,5]])
B2 = np.array([[4, 1],[9, 2],[2, 3],[3, 8],[3, 4],[3, 1]])
C = A1 @ B2
print(C)

[[ 95 129]
 [123  95]]
